### ISSUE TITLE
Add Karma support in combination with Travis CI

### ISSUE THREAD

**Issue by bennyn** [bennyn/generator-toe#6]
- http://www.sitepoint.com/testing-javascript-jasmine-travis-karma/
- http://karma-runner.github.io/0.8/plus/Travis-CI.html
- http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by bennyn** [comment]
**.travis.yml**

```yml
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "stable"

# http://docs.travis-ci.com/user/gui-and-headless-browsers
before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# http://docs.travis-ci.com/user/pull-requests/
script:
  - npm test
```
